### ISSUE TITLE
Issue compiling with VS2012

### ISSUE THREAD

**Issue by ghita** [phs/sauce#5]
I have issues compiling test code. Got this "helpful" error message (in ansi_compilation_test.cc, line: binder.bind<Animal>().named<Meatloaf>().toProvider<CowProvider()>();)

1>c:\dev\git\sauce\sauce\internal\implicit_bindings.h(107): error C2259: 'sauce::internal::ImplicitProviderBinding<ProvidedDependency,Name>' : cannot instantiate abstract class
1>          with
1>          [
1>              ProvidedDependency=Animal
1>  ,            Name=Meatloaf
1>          ]
1>          due to following members:
1>          'void sauce::internal::Binding<Dependency,Scope>::inject(std::shared_ptr<sauce::Provider<Animal>> &,std::shared_ptr<sauce::internal::ResolvedBinding<Dependency>>,sauce::internal::InjectorPtr) const' : is abstract
1>          with
1>          [
1>              Dependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            Scope=sauce::NoScope
1>          ]
1>          c:\dev\git\sauce\sauce\internal\binding.h(45) : see declaration of 'sauce::internal::Binding<Dependency,Scope>::inject'
1>          with
1>          [
1>              Dependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            Scope=sauce::NoScope
1>          ]
1>          c:\dev\git\sauce\sauce\internal\implicit_bindings.h(102) : while compiling class template member function 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>> sauce::internal::ImplicitBinding<Dependency>::get(const sauce::internal::Concrete &,const std::string)'
1>          with
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\implicit_bindings.h(62) : see reference to function template instantiation 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>> sauce::internal::ImplicitBinding<Dependency>::get(const sauce::internal::Concrete &,const std::string)' being compiled
1>          with
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\implicit_bindings.h(62) : see reference to class template instantiation 'sauce::internal::ImplicitBinding<Dependency>' being compiled
1>          with
1>          [
1>              Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\bindings.h(87) : see reference to function template instantiation 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>> sauce::internal::ImplicitBindings::getProviding<Dependency>(const sauce::internal::Concrete &,const std::string) const' being compiled
1>          with
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\bindings.h(119) : see reference to function template instantiation 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>> sauce::internal::Bindings<ImplicitBindings>::getProvidingBinding<Dependency>(const std::string) const' being compiled
1>          with
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            ImplicitBindings=sauce::internal::ImplicitBindings
1>  ,            Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\bindings.h(119) : see reference to function template instantiation 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>> sauce::internal::Bindings<ImplicitBindings>::getProvidingBinding<Dependency>(const std::string) const' being compiled
1>          with
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>  ,            ImplicitBindings=sauce::internal::ImplicitBindings
1>  ,            Dependency=Normalized
1>          ]
1>          c:\dev\git\sauce\sauce\internal\base_injector.h(70) : see reference to function template instantiation 'void sauce::internal::Bindings<ImplicitBindings>::validateAcyclic<Normalized>(bool,sauce::internal::Bindings<ImplicitBindings>::InjectorPtr,sauce::internal::TypeIds &,const std::string) const' being compiled
1>          with
1>          [
1>              ImplicitBindings=sauce::internal::ImplicitBindings
1>          ]
1>          c:\dev\git\sauce\sauce\internal\base_injector.h(70) : see reference to function template instantiation 'void sauce::internal::Bindings<ImplicitBindings>::validateAcyclic<Normalized>(bool,sauce::internal::Bindings<ImplicitBindings>::InjectorPtr,sauce::internal::TypeIds &,const std::string) const' being compiled
1>          with
1>          [
1>              ImplicitBindings=sauce::internal::ImplicitBindings
1>          ]
1>          c:\dev\git\sauce\sauce\injector.h(67) : see reference to function template instantiation 'void sauce::internal::BaseInjector<sauce::internal::ImplicitBindings>::validateAcyclic<Dependency>(bool,sauce::internal::BaseInjector<sauce::internal::ImplicitBindings>::InjectorPtr,sauce::internal::TypeIds &,const std::string) const' being compiled
1>          with
1>          [
1>              Dependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\injector.h(67) : see reference to function template instantiation 'void sauce::internal::BaseInjector<sauce::internal::ImplicitBindings>::validateAcyclic<Dependency>(bool,sauce::internal::BaseInjector<sauce::internal::ImplicitBindings>::InjectorPtr,sauce::internal::TypeIds &,const std::string) const' being compiled
1>          with
1>          [
1>              Dependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\injector.h(201) : see reference to function template instantiation 'void sauce::Injector::validateAcyclic<Dependency>(bool,sauce::internal::InjectorPtr,sauce::internal::TypeIds &,const std::string)' being compiled
1>          with
1>          [
1>              Dependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\internal\provider_binding.h(23) : see reference to function template instantiation 'void sauce::internal::InjectorFriend::validateAcyclicHelper<Provider>(sauce::internal::InjectorPtr,sauce::internal::TypeIds &,const std::string) const' being compiled
1>          with
1>          [
1>              Provider=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\internal\provider_binding.h(22) : while compiling class template member function 'void sauce::internal::ProviderBinding<ProvidedDependency,Scope,ProviderDependency>::validateAcyclic(sauce::internal::InjectorPtr,sauce::internal::TypeIds &) const'
1>          with
1>          [
1>              Scope=sauce::NoScope
1>  ,            ProviderDependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\binder.h(68) : see reference to class template instantiation 'sauce::internal::ProviderBinding<ProvidedDependency,Scope,ProviderDependency>' being compiled
1>          with
1>          [
1>              Scope=sauce::NoScope
1>  ,            ProviderDependency=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          c:\dev\git\sauce\sauce\binder.h(59) : while compiling class template member function 'void sauce::ToProviderClause<sauce::Named<sauce::Provider<Dependency>,Meatloaf>,sauce::NoScope,CowProvider (void)>::onComplete(void)'
1>          with
1>          [
1>              Dependency=Animal
1>          ]
1>          c:\dev\git\sauce\sauce\testansi.cpp(63) : see reference to class template instantiation 'sauce::ToProviderClause<sauce::Named<sauce::Provider<Dependency>,Meatloaf>,sauce::NoScope,CowProvider (void)>' being compiled
1>          with
1>          [
1>              Dependency=Animal
1>          ]
1>c:\dev\git\sauce\sauce\internal\implicit_bindings.h(107): error C2664: 'sauce::internal::ImplicitProviderBinding<ProvidedDependency,Name>::ImplicitProviderBinding(const sauce::internal::ImplicitProviderBinding<ProvidedDependency,Name> &)' : cannot convert parameter 2 from 'ProvidedBindingPtr' to 'std::shared_ptr<sauce::internal::ResolvedBinding<Dependency_>>'
1>          with
1>          [
1>              ProvidedDependency=Animal
1>  ,            Name=Meatloaf
1>          ]
1>          and
1>          [
1>              Dependency_=sauce::Named<sauce::Provider<Animal>,Meatloaf>
1>          ]
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>
1>Build FAILED.

**Comment by smithgeek** [comment]
Just in case anyone else is having this issue, I've submitted a fix for it https://github.com/phs/sauce/pull/10.

**Comment by phs** [comment]
Sauce requires at least MSVC 2015 to work correctly.  Good luck!
