### ISSUE TITLE
How to `get` an instance from injector, with non-default ctor?

### ISSUE THREAD

**Issue by dkrikun** [phs/sauce#7]
Hello,

I've defined a binding, like this one: `bind<Smth>().to<BestSmth(int,int)>()`.
Now, I've created a `Modules` and an `Injector`, and I want to create an instance of `Smth` according to the binding above, how could I do this?
Because:
```c++
shared_ptr<Smth> s = an_injector->get<BestSmth>(42, 42);
```
is an error, get does not takes args for `BestSmth` ctor.

Thanks!

**Comment by phs** [comment]
Closing as stale.
