### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by sumeet70** [phs/sauce#8]
Hi phs, first of all I would like to mention that this is great work. Basing your work and providing signature compatibility with guice is a smart choice.

I am having the same issue as #5 (already posted here). The code is failing when it is trying to create implicit provider binding during compile time.

**Comment by phs** [comment]
Keep an eye on #10 and #20, which should resolve this issue once we get them working.

**Comment by phs** [comment]
Closing as duplicate.
