### ISSUE TITLE
allocation_test failed on MinGW with GCC 4.4

### ISSUE THREAD

**Issue by lins05** [phs/sauce#9]
OS: WinXP SP3
ToolChain:  MinGW32 with GCC 4.4
version of Sauce:  master

The `test-suite.log` is [here](https://seacloud.cc/f/580e36e104/)

There is no problem with GCC 4.7.

**Comment by phs** [comment]
I believe this should be fixed by [88924d](https://github.com/phs/sauce/commit/88924d11dd141b9f06e015731802f9add7ada852), however that patch had to be reverted while I figure out some build portability issues.

**Comment by phs** [comment]
This should be fixed on master as of e9e5aad896e24d4223ac2cc2200a5d0b693a76ec
